### ISSUE TITLE
Unchecked state of Radio Buttons and Checkboxes look disabled

### ISSUE THREAD

**Issue by bramus** [RiskChallenger/open-components#6]
At a quick glance, the checkbox here looked `disabled` while it is not:

<img width="306" alt="image" src="https://user-images.githubusercontent.com/213073/234506714-3e24038f-2d41-48ee-94d9-f2fb3fdf28f7.png">

Especially when you compare it to the other components that have a white background when enabled and a dim background when not.

**Comment by rienheuver** [comment]
Completely agreed, this styling is off! A fix is underway, thanks for reporting this!

**Comment by bramus** [comment]
O yeah, much better. Thanks!
