### ISSUE TITLE
Tabs have no disabled state

### ISSUE THREAD

**Issue by Langstra** [RiskChallenger/open-components#8]
Would be nice to have a disabled state in case a tab is not available for a user, but should be visible. Or hasn't been implemented, but you still want to show it as a teaser.

**Comment by rienheuver** [comment]
Adding an option where you can add a `.disabled` class to a tab, preventing hover effects and adding a `not-allowed` cursor. It does not prevent click events however, so you'll have to make sure yourself you don't add event handlers
